server:
  port: 1122

spring:
  application:
    name: DemoRedisKafka
  #DBS
  datasource:
    hikari:
      maximum-pool-size: 10  # So luong toi da ket noi
      minimum-idle: 5        #  So luong ket noi toi thieu trong pool
    url: jdbc:mysql://localhost:3316/demo-redis-kafka
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Time
  jackson:
    time-zone: GMT+7 # Cau hinh gio
    serialization:
      indent-output: true

  # Redis
  data:
    redis:
      host: 127.0.0.1 # Host of the Redis server
      port: 6319 # Port of the Redis server for connection
      password: ""  # Password for connecting to the Redis server (default is empty)

  kafka:
    bootstrap-servers: 192.168.1.163:9193 #Todo: Sua lai ip
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: synchronous-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    properties:
      allow:
        auto:
          create:
            topics: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.boot.context.properties: DEBUG

jwt:
  expire:
    token: 86400000
    refreshToken: 604800000

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

com:
  lucas:
    kafka:
      synchronous:
        requestTopic: dispatch-request
        replyTopic: dispatch-response
        replyTimeout: 30s
