server:
  port: 1122

spring:
  application:
    name: DemoRedisKafka
  #DBS
  datasource:
    hikari:
      maximum-pool-size: 10  # So luong toi da ket noi
      minimum-idle: 5        #  So luong ket noi toi thieu trong pool
    url: jdbc:mysql://localhost:3316/demo-redis-kafka
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  #JPA
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  # Time
  jackson:
    time-zone: GMT+7 # Cau hinh gio
    serialization:
      indent-output: true

  # Redis server connection settings
  #  data:
  #    redis:
  #      host: redis-12754.c1.ap-southeast-1-1.ec2.redns.redis-cloud.com # Host of the Redis server
  #      port: 12754 # Port of the Redis server for connection
  #      password: "eV1rqBUEPzcZd1WJoZZwV9tbwZLhRJTe"  # Password for connecting to the Redis server (default is empty)
  data:
    redis:
      host: 127.0.0.1 # Host of the Redis server
      port: 6319 # Port of the Redis server for connection
      password: ""  # Password for connecting to the Redis server (default is empty)

  #Kafka
  kafka:
    bootstrap-servers: 192.168.1.48:9193
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: demoRedisKafka
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


jwt:
  expirationTimeToken: 24 * 60 * 60 * 1000 # 1 ngay
  expirationTimeRefreshToken: 7 * 24 * 60 * 60 * 1000 # 7 ngay
